export const ADD_COUNTER_REQUEST = 'ADD_COUNTER_REQUEST'
export const ADD_COUNTER_SUCCESS = 'ADD_COUNTER_SUCCESS'

export const SUB_COUNTER_REQUEST = 'SUB_COUNTER_REQUEST'
export const SUB_COUNTER_SUCCESS = 'SUB_COUNTER_SUCCESS'